[package]
name = "adder"
version = "0.1.0"
authors = ["Kay <redl0tus@noreply.github.com>"]

[dependencies]
add-one = { path = "../add-one" }
add-two = { path = "../add-two" }
add-rand = { path = "../add-rand" }
